ENH: Show colors in terminology selector
Slicer/Slicer pull request #5416
Opened 2021-01-29 10:27 UTC by cpinter

The recommended colors for are shown as a color square for each type in the terminology navigator widget.

![image](https://user-images.githubusercontent.com/1325980/106263622-841c8500-621c-11eb-9589-d1106a41f631.png)

2021-01-29 14:29 UTC, lassoan approved these changes
This looks great, thank you!

2021-01-29 14:29 UTC, lassoan commented on Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
> +  {
indentation

2021-01-29 15:45 UTC, cpinter commented
I fixed the indentation and added a check not to show color if the type did not have a color to begin with, like this
![image](https://user-images.githubusercontent.com/1325980/106296012-091d9380-6249-11eb-84c6-1730dca37947.png)

2021-01-29 15:48 UTC, lassoan commented
When does it happen that the type does not have a color? When it has a modifier? In that case, it would be better to show the first available color (usually they are the same or very similar for all modifiers).

2021-01-29 15:50 UTC, cpinter commented
Yes it happens when they have modifiers. I think I can get the first modifier. Not sure how much it will slow things down, probably not noticeably.

2021-01-29 16:27 UTC, cpinter commented
Done, the first modifier's color is used if found.

2021-01-30 18:53 UTC, lassoan requested changes
This will be good, there is just a build error on linux according to CircleCI.

2021-02-02 11:41 UTC, cpinter commented
I fixed the error.

2021-02-02 13:04 UTC, lassoan approved these changes

2021-02-02 13:05 UTC, lassoan commented
Thank you!

2021-02-02 13:43 UTC, merged