ENH: Add properties for easy visibility setting of SH tree columns
Slicer/Slicer pull request #5430
Opened 2021-02-03 13:55 UTC by cpinter

Instead of
`self.ui.SubjectHierarchyTreeView.setColumnHidden(self.ui.SubjectHierarchyTreeView.model().idColumn, True)`
we can now use
`self.ui.SubjectHierarchyTreeView.idColumnVisible = False`

2021-02-08 15:46 UTC, lassoan approved these changes
Very nice simplification, thank you.
Just for completeness, would you add visibility and and description columns as well?

2021-02-08 16:22 UTC, cpinter commented
Makes sense, I added the description column visibility property as well.

2021-02-08 19:38 UTC, lassoan submitted a review, later dismissed
>  visibility and and description

Was there any specific reason you did not include visibility column? Not a big issue, we can merge as is, but it would be nice to be able to consistently show/hide all volumes.

2021-02-09 07:51 UTC, cpinter commented
You're right there is no good reason. Initially I thought visibility is always needed and forgot about the new description column. But it's indeed better to include all of them for consistency.

2021-02-09 13:42 UTC, lassoan requested changes
Thank you, almost there!

2021-02-09 13:42 UTC, lassoan commented on Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
> +  return !this->isColumnHidden(this->model()->idColumn());
Copy-paste error
```suggestion
  return !this->isColumnHidden(this->model()->visibilityColumn());
```

2021-02-09 13:53 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qMRMLSubjectHierarchyTreeView.cxx
> +  return !this->isColumnHidden(this->model()->idColumn());
Bah... ok :)

2021-02-09 17:17 UTC, lassoan approved these changes
Looks good, thank you!

2021-02-09 17:18 UTC, merged