ENH: Add RenderBlocker context manager to call pauseRender/resumeRender
Slicer/Slicer pull request #5865
Opened 2021-09-16 02:23 UTC by Sunderlandkyl

This commit adds a context a manager that calls slicer.app.pauseRender() on enter and slicer.app.resumeRender() on exit.

Previously this would be written as:
```
try:
  slicer.app.pauseRender()
  # Do things
finally:
  slicer.app.resumeRender()
```

Now can be written as:
```
with slicer.util.RenderBlocker():
  # Do things
```

2021-09-16 02:33 UTC, lassoan reviewed
Thank you, This looks good to me.

Could you add the excellent usage example to the class documentation?

Also describe there why blocking the rendering is useful (to improve performance and ensure consistency of all view contents - prevent all renderings until all computations in the code block are completed).

2021-09-25 02:41 UTC, lassoan requested changes
Setting the state to "request changes" to make it more clear that code update is needed (and not code review).

2021-09-27 17:46 UTC, lassoan commented
@Sunderlandkyl let me know if you prefer if I make the little requested change. We would like to close all the pending pull requests so that we can better see which requires review or more work. Thank you.

2021-09-27 17:53 UTC, Sunderlandkyl commented
Sorry, forgot about this PR. I'll update it in a minute.

2021-09-27 18:16 UTC, Sunderlandkyl commented
Ok. it should be updated.

2021-09-27 18:39 UTC, lassoan approved these changes
Thank you!

2021-09-27 18:40 UTC, merged