ENH: Add deprecation warnings to deprecated Markups API methods
Slicer/Slicer pull request #6023
Opened 2021-11-12 18:02 UTC by jamesobutler

This closes #5990 by providing warnings of deprecated methods. Developers are alerted of the deprecation at runtime which is a lot more helpful than only documented in the source code.

Deprecation with runtime warnings is like what is already done for `SetSliceIntersectionVisibility`.

https://github.com/Slicer/Slicer/blob/6582c1f0b0ec5772776564e5c2704e78b82ea261/Libs/MRML/Core/vtkMRMLDisplayNode.cxx#L932-L935

2021-11-16 04:20 UTC, lassoan requested changes
Thank you! Apart from a few trivial things (see inline comments) it looks good to me.

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialNodeTest1.cxx
> +  int fidIndex = node1->AddControlPoint(inPosVector, std::string());
Use vtkVector3d constructor as above

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialNodeTest1.cxx
>    double diff = sqrt(vtkMath::Distance2BetweenPoints(inPos, outPos));
```suggestion
  double diff = sqrt(vtkMath::Distance2BetweenPoints(inPos, posVector.GetData()));
```

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialNodeTest1.cxx
> +  outPos[1] = posVector.GetY();
No need for these copies, double* can be accessed via `posVector.GetData()`.

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialStorageNodeTest2.cxx
> +  outputPoint[1] = posVector.GetY();
no need for these, just use `posVector.GetData()`

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMRMLMarkupsFiducialStorageNodeTest3.cxx
> +  outputPoint[1] = posVector.GetY();
use .GetData()

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMarkupsAnnotationSceneTest.cxx
> +  markupPosition[1] = posVector.GetY();
.GetData()

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkMarkupsAnnotationSceneTest.cxx
> +  markupPosition2[1] = posVector2.GetY();
.GetData()

2021-11-16 04:20 UTC, lassoan commented on Modules/Loadable/Markups/Testing/Cxx/vtkSlicerMarkupsLogicTest3.cxx
> +      pos[1] = posVector.GetY();
.GetData()

2021-11-16 17:27 UTC, jamesobutler commented
I've re-requested review @lassoan following updates to fix your inline comments.

2021-11-17 22:21 UTC, lassoan approved these changes
It looks good, thank you!

2021-11-17 22:21 UTC, merged

2021-11-17 22:56 UTC, jcfr commented
re: deprecation

I also found the approach of Qt particularly effective in term of compiler warnings. 

For example:

```
  /path/to/S-r/CTK/Libs/Core/ctkErrorLogQtMessageHandler.cpp:70:57: warning: 'load' is deprecated: Use loadRelaxed [-Wdeprecated-declarations]
    if (ctkErrorLogQtMessageHandler_CurrentRecursionDepth.load() > 10)
                                                          ^
  /path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qbasicatomic.h:103:5: note: 'load' has been explicitly marked deprecated here
      QT_DEPRECATED_VERSION_X_5_14("Use loadRelaxed") T load() const noexcept { return loadRelaxed(); }
      ^
  /path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h:366:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_14'
  # define QT_DEPRECATED_VERSION_X_5_14(text) QT_DEPRECATED_X(text)
                                              ^
  /path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
  #  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                  ^
  /path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
  #    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                        ^
```

See https://github.com/qt/qtbase/blob/bbfd625b6351f0a28fd1f2894ed92b8da6d97c97/src/corelib/global/qglobal.h#L372-L378

I found the suggestion provided in the compiler warnings to be useful.

2021-11-17 23:36 UTC, lassoan commented
Most people use the Slicer API from Python, so runtime warnings are more important, but it would be nice to add build-time warnings as well.