ENH: reset IJK matrix in volume information
Slicer/Slicer pull request #6120
Opened 2022-01-20 13:15 UTC by riep

IJK matrix is not reset when selecting an empty volume node

2022-01-20 14:31 UTC, lassoan requested changes
Thank you, it looks good, just added two nitpicky comment inline (they are very easy to fix).

2022-01-20 14:31 UTC, lassoan commented on Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
> +    double IJKToRASDirections[3][3] = { {1,0,0}, {0,1,0}, {0,0,1} };
Double values should be initialized with double (`1.0` or just `1.`). But I would rather remove this line and just use `i==j ? 1.0 : 0.0`). Also add a comment that we are setting the matrix to identity.

2022-01-20 14:31 UTC, lassoan commented on Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
> +    {
I don't like Slicer's current brace indentation style, but for consistency, please use that (indent the `{` by two spaces).

2022-01-21 11:41 UTC, riep commented
corrections done

2022-01-23 04:46 UTC, lassoan commented on Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
> +    double IJKToRASDirections[3][3];
Is `IJKToRASDirections` still needed?

2022-01-23 05:59 UTC, riep commented on Libs/MRML/Widgets/qMRMLVolumeInfoWidget.cxx
> +    double IJKToRASDirections[3][3];
sorry, this is corrected

2022-01-23 14:51 UTC, lassoan approved these changes
Perfect, thank you.

2022-01-23 14:51 UTC, merged