BUG: Fix attribute bad access in when using a sequence node
Slicer/Slicer pull request #6254
Opened 2022-03-08 21:49 UTC by xriobe

In DICOMScalarVolumePluginClass::sliceCornersFromDICOM, the DICOM.instanceUIDs attribute will be empty in this case.

2022-03-08 22:01 UTC, pieper requested changes
Thanks for the contribution 👍 

Can you add a bug report that describes what situation this fixes?  Then reference that bug report here so that we can close the bug with the PR merge.

It seems to me that the only way the `DICOM.instanceUIDs` attribute would be missing would be if this code were used from outside the DICOM module - is that how this came up?

2022-03-08 22:11 UTC, xriobe commented
Yes this occurs when using the method independently, that's why I did not enter a bug for Slicer since it may not be reproducible, but this modification improves robustness.

2022-03-08 22:15 UTC, pieper commented
Thanks for the extra information.  Since these methods are part of the public API even if they were originally intended for internal use it does make sense to make them robust.   Since the change is small and clear I guess we don't need a bug report since developers could always find this PR if context is needed.

2022-03-09 09:14 UTC, xriobe commented
So i guess there is no more change requested? The fail of the API documentation should not be related to this.

2022-03-09 11:35 UTC, closed without merging

2022-03-09 12:40 UTC, xriobe commented
oups, bad manipulation in my fork, see https://github.com/Slicer/Slicer/pull/6259