Allow removing subject hierachy plugin
Slicer/Slicer pull request #6299
Opened 2022-04-04 07:00 UTC by riep

This development comes from the need to remove the right click on markups (in MPR views) in a slicelet application.
It is also important to avoid switching into slicer when clicking on "edit properties" action.

2022-04-04 11:06 UTC, jamesobutler commented
Using the currently available allowed list of context menu actions not enough control for you? https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#use-whitelist-to-customize-view-menu

2022-04-04 11:29 UTC, riep commented
I think his code is deprecated and is replaced by https://github.com/Slicer/Slicer/commit/62fe31fb179e5c904f5d8157739483dee6669a44

This is an interesting feature that I have looked into. For our application, it has the following limitations:
1. Cannot have empty list of actions.
2. Is reset after right click in a subject hierarchy tree view. (Actions on right click are filtered only after having selected the markup (with left click).

2022-04-04 11:52 UTC, cpinter requested changes
The main problem is that the unregister function does not do what its name suggests (it does not actually unregisters plugins). I also added minor comments.

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
> +    for(int i = 0; i < viewMenuActionsCount; i++)
Space between `for` and `(`

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
> +      }
Error handling would be nice

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx
> +  /// Enable properties action
Enable Edit properties action

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h
> +  Q_INVOKABLE bool unRegisterPlugin(QString name);
Looking at other Qt classes the function name should be `unregisterPlugin`

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx
> +    this->m_PluginLogic->unRegisterViewMenuAction(action);
This function does not actually unregister plugins, it only removes the view actions provided by the given plugin! There are much more to plugins than doing this  (there are other types of actions, there is a list of registered plugins in this class etc). Please look at what `registerPlugin` does (and the abstract SH plugin class to see what they provide and what needs to be removed) and finish this function. Or rename it to make it obvious what it does and what it doesn't.

2022-04-04 11:52 UTC, cpinter commented on Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.h
> +  Q_INVOKABLE void setEditPropertiesEnabled(bool enable);
If you have a setter function you need to add a getter function too. Also make it a Qt property.

2022-04-04 11:53 UTC, cpinter commented
In general, I think it would best to use the whitelist/blacklist feature as @jamesobutler suggests. If it has bugs, then generally it would be better to fix those bugs than adding a feature working around those bugs.

2022-04-04 14:44 UTC, lassoan commented
I agree, we should fix the existing mechanisms instead of introducing a new one. We can already customize/disable "Edit properties" at two granularity levels:
- for all items: use action whitelist
- for selected items (can be used for all items, too): create a plugin that owns the subject hierarchy item (by returning high confidence value for `canOwnSubjectHierarchyItem`) and then return `false` for `canEditProperties`.

Probably the whitelist method would be more appropriate for your use case. The [two limitations](https://github.com/Slicer/Slicer/pull/6299#issuecomment-1087440273) seem like bug/minor improvement that should not be hard to fix.

2022-04-08 11:25 UTC, closed without merging

2022-04-08 11:26 UTC, riep commented
I will reopen this PR if needed