COMP: Do not require building extension from git repository
Slicer/Slicer pull request #6365
Opened 2022-05-12 01:56 UTC by lassoan

Developers often complained that their extension build failed for some unknown reason and frequently the issue was that they did not store the source code in a git repository.

It is good to encourage developers to use best practices, such as version control, but making the build fail if they build from a non-version-controlled repository was unnecessarily strong measure.

This commit changes the behavior so that if an extension is built from a non-git folder then the build succeeds, just a warning is displayed during project configuration step and `NA` is used as the extension's WC revision.

2022-05-12 02:00 UTC, pieper commented
This makes sense to me - I'll leave it to @jcfr to decide if it's a good move.

2022-05-12 06:30 UTC, jcfr requested changes
Since directly updating `CMake/SlicerMacroExtractRepositoryInfo.cmake` would also mean we can build custom application without having the code associated with git repo, this would have to be further improved.

To simply accommodate the extension use case, I instead suggest to consider a different approach. See https://github.com/Slicer/Slicer/pull/6369

2022-05-13 17:58 UTC, jcfr commented
Since this was inadvertently integrated as part of https://github.com/Slicer/Slicer/pull/6371/, I am closing and will revert in https://github.com/Slicer/Slicer/pull/6369

2022-05-13 17:58 UTC, closed without merging

2022-05-13 18:15 UTC, lassoan commented
> Since this was inadvertently integrated as part of #6371, I am closing and will revert in #6369

Yes, sorry, I tested that change in my working copy and I did not noticed that it got in with this commit. I'm not sure if https://github.com/Slicer/Slicer/pull/6369 is what we need - I'll add a comment there.