Left Mouse 'click-and-drag' to shift between 2d pics test ok
Slicer/Slicer pull request #6497
Opened 2022-08-11 02:42 UTC by simzhangbest

left mouse click-and-drag to shift between 2d pics finished, but not too smooth

2022-08-11 14:31 UTC, pieper commented on Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx
> +    const double CONF = 0.01;
Rather than hard-code this, it would be better to make it a function of the window size using the same code as `ProcessZoomSlice`.

2022-08-11 14:37 UTC, pieper requested changes
I'm thinking this makes sense as a left button mouse action, but it's a question whether it should be on by default or maybe be a user preference setting.  Changing window/level used to be the default but we disabled it because it was too easy to accidentally change it when trying to click on a Markup.  I wonder if this would have the same issue.  @lassoan @jcfr @jamesobutler

2022-08-11 14:37 UTC, pieper commented on Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.h
> +  bool ProcessIncDecSlice(vtkMRMLInteractionEventData* eventData);
`IncDec` wasn't clear to me on first reading.  Maybe better to call this `Scroll` mode (this would need to be changed everywhere).

2022-08-11 14:37 UTC, pieper commented on Libs/MRML/DisplayableManager/vtkMRMLSliceIntersectionWidget.cxx
> +    // else this->DecrementSlice();
We don't like to leave dead code in the source so this should be removed once the functionality is in place.

2022-08-11 14:48 UTC, jamesobutler commented
Yes the default mouse mode should be just the regular arrow cursor mode for clicking/translating things. A new mouse mode for manipulating slice offset with left click could be an option though.

2022-10-11 14:54 UTC, pieper commented
@simzhangbest are you still able to work on this?  I like the idea of having a stack-scroll mode but we'd need to address the comments above.

2022-10-18 14:40 UTC, lassoan commented
This will be a useful feature, but needs more work. I'm closing this PR to reduce the number of open PRs, but we are happy to reopen if you can work on it a bit more.

2022-10-18 14:40 UTC, closed without merging