DOC: Clarify description of volume computation in Segment statistics
Slicer/Slicer pull request #6739
Opened 2022-12-18 16:38 UTC by lassoan

2022-12-18 18:25 UTC, pieper requested changes
A few small suggestions.

2022-12-18 18:25 UTC, pieper commented on Docs/user_guide/modules/segmentstatistics.md
> +The values are computed from the binary labelmap representation of the segment, for the part that verlaps with the chosen scalar volume.
```suggestion
The values are computed from the binary labelmap representation of the segment, for the part that overlaps with the chosen scalar volume.
```

2022-12-18 18:25 UTC, pieper commented on Docs/user_guide/modules/segmentstatistics.md
>  - [Segmentations](segmentations.md) module allows changing visualization options, exporting/importing segments to/from other nodes (models, labelmap volumes), and moving or copying segments between s
```suggestion
- [Segmentations](segmentations.md) module allows changing conversion options, such as decimation and smoothing when converting from labelmap to closed surface representations, which are mainly for visualization, but can have an impact on some statistics such as volume and surface area.  The Segmentations module can also be used for exporting/importing segments to/from other nodes (models, labelmap volumes), and moving or copying segments between segmentation nodes.
```

2022-12-21 05:46 UTC, jcfr commented on Docs/user_guide/modules/segmentstatistics.md
> +There are several ways of computing volume and surface of a segment. The main difference is what is the representation used (3D binary image or surface mesh) and if the entire segment is used or only
```suggestion
There are several ways of computing volume and surface of a segment. The main difference relates to the representation being used (3D binary image or surface mesh) and if the entire segment is used or only the part that overlaps with the selected scalar volume. Difference between the values should be very small, less than one percent, so it usually does not matter which one is used. Usually it does not matter which plugin is used, but to minimize variance between values, it is recommended to consistently use the same plugin within a study.
```

2022-12-21 05:46 UTC, jcfr commented on Docs/user_guide/modules/segmentstatistics.md
>  - Volume cm3 the volume of the segment in cm3
```suggestion
- Volume mm3: the volume of the segment in mm3
- Volume cm3: the volume of the segment in cm3
```

2022-12-21 05:46 UTC, jcfr commented on Docs/user_guide/modules/segmentstatistics.md
> +- If scalar volume input is set in the module then `Scalar volume` plugin computes image intensity statistics for each segment. In this case, using values provided by the `Scalar volume` plugin makes
```suggestion
- If the scalar volume input is set in the module then the `Scalar volume` plugin computes image intensity statistics for each segment. In this case, using values provided by the `Scalar volume` plugin makes sense. Surface and volume values are computed by the same method as in `Labelmap` plugin, the only difference is that the values are computed for only that part of the segments that overlap with the scalar volume.
```

2022-12-21 05:46 UTC, jcfr commented on Docs/user_guide/modules/segmentstatistics.md
> +- `Labelmap` plugin is a good choice for computing volume of a segment for most cases. The volume is computed from the number of voxels multiplied by the volume of a singlevoxel. By default, surface
```suggestion
- The `Labelmap` plugin is a good choice for computing the volume of a segment for most cases. The volume is computed from the number of voxels multiplied by the volume of a singlevoxel. By default, surface computation in `Labelmap` plugin is disabled - either enable `Surface mm2` measurement in advanced settings to make this plugin compute surface area; or click `Show 3D` button to create closed surface representation for the segment and then get surface area from `Closed surface` plugin.
```

2022-12-22 21:13 UTC, merged