ENH: One draw effect point does not prevent use in other slice offset
Slicer/Slicer pull request #6997
Opened 2023-05-31 22:47 UTC by jamesobutler

If you are in the "Draw" segment editor effect and click to place one point in the given slice offset and then you scroll to another slice offset, you will be unable to place more draw effect points in that offset. It is confusing because that single point does not create an visual UI element, so you are left confused that you actually had started drawing on another slice offset. You currently have to right-click to apply (which does nothing because there is <2 points) and then you can draw on the new slice offset. 

This was leading to confusion by our group's users. I have added code so that if you have placed a single point and then scroll to another slice offset, then the draw effect's points are cleared/reset. 

I still think it is a little confusing when there are >1 points and the draw effect goes into a "dashed" line state which is difficult to see and then right-click to apply brings it to the new slice offset. It currently looks like a graphical issue. I would rather the draw effect lines stay the same and then pressing right-click continues to bring the shape to the new slice offset.

2023-06-01 20:48 UTC, jamesobutler commented
> I still think it is a little confusing when there are >1 points and the draw effect goes into a "dashed" line state which is difficult to see. It currently looks like a graphical issue. I would rather the draw effect lines stay the same.

Below is the code being referenced in regards to the display of the draw effect after changing slice offset.
https://github.com/Slicer/Slicer/blob/5e7d60c87711a14902f9001330321e1e494a7e6b/Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorDrawEffect.py#L123-L132

2023-06-27 17:13 UTC, jamesobutler commented
The dashed line doesn't really work when using the draw tool in a continuous point placing mode (left+click-and-drag). As shown below it very much looks like a rendering issue. 

![image](https://github.com/Slicer/Slicer/assets/15837524/b0dd4520-7a0a-4c43-999b-4d1e6584bc01)
![image](https://github.com/Slicer/Slicer/assets/15837524/338a8cd8-479b-497b-b4e3-37772352b8b1)

The dashed rendering is better when placing individual points where there are longer distances between points.
![image](https://github.com/Slicer/Slicer/assets/15837524/fe86e4b9-540e-4a16-9893-e31ea0bbc4b4)

2023-07-12 02:45 UTC, lassoan commented
Allowing users to peek into neighbor slices during drawing is a very useful feature, but I agree that the dashed line appearance is not clear enough (and when the line segments are too short - for example due to continuous drawing). @jamesobutler do you have an idea how we could preserve this feature but make it more clear to users how it works?

2023-07-12 03:00 UTC, jamesobutler commented
> Allowing users to peek into neighbor slices during drawing is a very useful feature

I think it would be logical to support drawing on the 2D viewport and allow scrolling to other slice offsets and maintain points (if n>1). Applying the end interaction however would apply to the current offset. Scrolling to another slice and then wanting to apply would seem confusing to a user that it isn’t applying at their current slice.

Otherwise changing the color of the draw lines instead of changing to dashed could indicate it was drawn on a non-active slice offset.

2023-07-12 14:11 UTC, pieper commented
Another option would be to change the cursor to something like an arrow with an X when you scroll away from the slice where the drawing will take place.

2023-07-12 14:26 UTC, jamesobutler commented
So currently if you place some points with the draw effect and then scroll to another slice offset, the display changes to dashed lines. From that new slice offset you cannot draw new points, but you can apply the drawing and it will apply to that new slice offset, not the original slice offset. 

Therefore what is the meaning of changing the draw lines to dashed and preventing placing of new points if you are allowed to apply the dashed drawing to the new slice offset? Using a forbidden cursor when changing the slice offset would seem like the desire is to prevent applying the drawing on an offset where it was not originally drawn on? Is that a bug?

2023-07-12 14:34 UTC, pieper commented
> but you can apply the drawing and it will apply to that new slice offset, not the original slice offset.

Yes, this seems like a bug to me.  I would expect it to apply to the original slice.

2023-07-12 14:42 UTC, jamesobutler commented
Is it reasonable to clear the points if only 1 is placed and the slice offset is changed (`ENH: One draw effect point does not prevent use in other slice offset` in this PR)? Essentially defining that the drawing is invalid and not locking it to a slice offset. 

Or should the individual point be maintained, but don't prevent placing new points on a new slice offset? This would bring that first point to the new offset where the second point was placed and locking it in there.

2023-07-12 14:58 UTC, jamesobutler commented
Is this commit in this PR good to integrate? We have had customers specifically run into this issue of placing a point in a slice view, then changing slice offset being confused why the "draw effect was broken".

2024-10-08 16:51 UTC, pieper requested changes
Were you able to test this? I'm thinking that resetting the polydata should only happen if you are not on the active slice (i.e. when `if offset > 0.01:` is true).  Currently it looks like it would always reset a single point when a slice node event comes in, such as panning or something.

2024-10-08 17:13 UTC, jamesobutler commented
Yes I tested this and demo'd it working during the hangout meeting. I'm not sure if you had joined the meeting at that time.

2024-10-08 17:17 UTC, pieper commented
Okay, then I think just moving the code down into that if clause is all we need.

2024-10-08 17:37 UTC, pieper approved these changes
LGTM 👍

2024-10-08 18:50 UTC, merged