ENH: Change read/write XML in vtkMRMLSliceNode to use macros
Slicer/Slicer pull request #7039
Opened 2023-06-22 17:31 UTC by stephencrowell

`vtkMRMLSliceNode`'s read and write XML did not use macros. As I was updating the XML attributes as part of #7021, we decided to update all XML attributes before adding the new items.

2023-06-22 17:39 UTC, pieper submitted a review, later dismissed
Makes sense to me to clean up this code.  Is there test coverage for this?

2023-06-22 17:42 UTC, jcfr commented
To provide some context, I suggested @stephencrowell to work on this after realizing the class was still using the "legacy" and more verbose approach.

Once this is done, the plan is to rebase and update the following pull request:
* #7021

2023-06-22 17:44 UTC, jcfr commented on Libs/MRML/Core/vtkMRMLSliceNode.cxx
> +  vtkMRMLWriteXMLStdFloatVectorMacro(uvwDimensions, UVWOrigin, double);
```suggestion
  vtkMRMLWriteXMLStdFloatVectorMacro(uvwOrigin, UVWOrigin, double);
```

2023-06-22 17:45 UTC, jcfr commented on Libs/MRML/Core/vtkMRMLSliceNode.cxx
> +  vtkMRMLWriteXMLStdStringVectorMacro(threeDViewNodeRef, ThreeDViewIDs, std::string);
To ensure the MRML scene are identically serialized, this should be moved after `orientationMatrix`

2023-06-22 17:47 UTC, jcfr commented on Libs/MRML/Core/vtkMRMLSliceNode.cxx
> +  vtkMRMLWriteXMLIntMacro(widgetVisibility, WidgetOutlineVisible);
```suggestion
  vtkMRMLWriteXMLIntMacro(widgetOutlineVisibility, WidgetOutlineVisible);
```

2023-06-22 18:34 UTC, jcfr requested changes
Thanks for working on this :pray: 

Before we can integrate:
* Consider using `vtkMRML*XMLBooleanMacro` where it applies
* Ensure that order of attribute remains the same
* Locally run the related tests `ctest -R vtkMRMLSlice`

2023-06-22 19:18 UTC, stephencrowell commented
I added the macros to `Copy` and `PrintSelf` while we were making changes.

The local tests passed without issue when ran locally.

2023-06-28 15:06 UTC, jcfr commented
@stephencrowell To streamline the review process, I ended up squashing the commit together.

2023-06-28 15:07 UTC, jcfr commented
Comparing the scene before/after:

![image](https://github.com/Slicer/Slicer/assets/219043/974b4f70-c231-4529-983e-81984591e16f)

2023-06-28 15:25 UTC, stephencrowell commented
> Comparing the scene before/after:

Looks like the previous version just put the enum value where I used enum macro. I'll change it the int macro to match the previous.

2023-06-28 20:20 UTC, jcfr commented
Differences associated with the output of `print(getNode("vtkMRMLSliceNodeRed"))`:

```diff
diff --git a/print.txt b/print.txt
index 711ae5d..23f2d7b 100644
--- a/print.txt
+++ b/print.txt
@@ -27,27 +27,21 @@ vtkMRMLSliceNode (0xFFFFFFF)
   RulerType: none
   RulerColor: white
    AxisLabels: L;R;P;A;I;S
-  FieldOfView:
-      561.404     256     1
-  Dimensions:
-      500     228     1
-  XYZOrigin:
-      0     0     0
-  UVWDimensions:
-      256     256     1
-  UVWExtents:
-      561.404     256     1
-  UVWOrigin:
-      0     0     0
+  FieldOfView: (561.404, 256, 1)
+  Dimensions: (500, 228, 1)
+  XYZOrigin: (0, 0, 0)
+  UVWDimensions: (256, 256, 1)
+  UVWExtents: (561.404, 256, 1)
+  UVWOrigin: (0, 0, 0)
   SliceResolutionMode: 1
   Layout grid: 1x1
-  Active slice: 0
+  ActiveSlice: 0
   SliceVisible: false
   WidgetVisible: false
   WidgetOutlineVisible: true
   UseLabelOutline: false
   Jump mode:   Offset
-  SliceToRAS: 
+  SliceToRAS:
     Debug: Off
     Modified Time: 999999
     Reference Count: 1
@@ -94,7 +88,7 @@ vtkMRMLSliceNode (0xFFFFFFF)
         0 1.12281 0 -121.571 
         0 0 1 -10.2143 
         0 0 0 1 
-  Slice spacing mode: Automatic
-  Prescribed slice spacing: (1, 1, 1)
+  SliceSpacingMode: Automatic
+  PrescribedSliceSpacing: (1, 1, 1)
   Interacting: off
   DefaultOrientation: Axial

```

2023-06-28 20:24 UTC, jcfr commented
In term of MRML scene saving, the only difference is one space when serializing `sliceToRAS`:

![image](https://github.com/Slicer/Slicer/assets/219043/3d7ec053-7870-43b3-ba33-d18c0ad534ab)

2023-06-28 20:30 UTC, jcfr commented
@Sunderlandkyl When you introduced `vtkMRMLWriteXMLMatrix4x4Macro` in e234c65d9a, did you intended separating each "row" with two spaces ? Or was this an oversight ?

2023-06-28 20:32 UTC, Sunderlandkyl commented
I don't recall. It was likely unintentional.

2023-06-28 20:43 UTC, jcfr commented
Thanks for the follow up, I will update the macro to have only one space then.

Since there are no mrml scenes with the `interactionHandleToWorldMatrix` checked in the source tree (and many with `sliceToRAS` attribute), it will be easy to address.

Also worth noting that the reading of the attribute values should not be impacted.

2023-06-29 05:52 UTC, jcfr approved these changes

2023-06-29 13:22 UTC, jcfr commented
After locally rebuilding, I confirm the MRML scene are identical:

![image](https://github.com/Slicer/Slicer/assets/219043/67e90634-3b04-4107-9e7e-202d30be046a)


And different with the output `PrintSelf` is also acceptable:

```diff
diff --git a/print.txt b/print.txt
index 711ae5d..23f2d7b 100644
--- a/print.txt
+++ b/print.txt
@@ -27,27 +27,21 @@ vtkMRMLSliceNode (0xFFFFFFF)
   RulerType: none
   RulerColor: white
    AxisLabels: L;R;P;A;I;S
-  FieldOfView:
-      561.404     256     1
-  Dimensions:
-      500     228     1
-  XYZOrigin:
-      0     0     0
-  UVWDimensions:
-      256     256     1
-  UVWExtents:
-      561.404     256     1
-  UVWOrigin:
-      0     0     0
+  FieldOfView: (561.404, 256, 1)
+  Dimensions: (500, 228, 1)
+  XYZOrigin: (0, 0, 0)
+  UVWDimensions: (256, 256, 1)
+  UVWExtents: (561.404, 256, 1)
+  UVWOrigin: (0, 0, 0)
   SliceResolutionMode: 1
   Layout grid: 1x1
-  Active slice: 0
+  ActiveSlice: 0
   SliceVisible: false
   WidgetVisible: false
   WidgetOutlineVisible: true
   UseLabelOutline: false
   Jump mode:   Offset
-  SliceToRAS: 
+  SliceToRAS:
     Debug: Off
     Modified Time: 999999
     Reference Count: 1
@@ -94,7 +88,7 @@ vtkMRMLSliceNode (0xFFFFFFF)
         0 1.12281 0 -121.571 
         0 0 1 -10.2143 
         0 0 0 1 
-  Slice spacing mode: Automatic
-  Prescribed slice spacing: (1, 1, 1)
+  SliceSpacingMode: Automatic
+  PrescribedSliceSpacing: (1, 1, 1)
   Interacting: off
   DefaultOrientation: Axial
```

2023-06-29 13:23 UTC, merged