BUG: mark translatable string see ->SlicerLanguagePacks/issues #12
Slicer/Slicer pull request #7283
Opened 2023-10-13 11:19 UTC by Papa96108

2023-10-25 15:32 UTC, jcfr requested changes
Overall the changes look good.

Before integrating, I suggest to have two commits:
- `ENH: Improve TableNode API for column title`
- `ENH: Make Table module translatable`
` `ENH: Make SegmentStatistics measurement translatable`

### Questions

* Will the update changing `SCHEMA_COLUMN_LONG_NAME` to `SCHEMA_COLUMN_TITLE` impact loading of table saved using the older column name ?


### Notes

When referencing issues outside of the Slicer project make sure to use the format `Organization/Repository#IssueNumber`, failure to do so is referencing issue in the "wrong" project.

See more details at https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls

2023-10-25 15:32 UTC, jcfr commented on Libs/MRML/Core/vtkMRMLTableNode.cxx
> +  vtkWarningMacro("This method is deprecated and will be unavailable soon. Please use SetColumnTitle instead");
```suggestion
  vtkWarningMacro("vtkMRMLTableNode::SetColumnLongName is deprecated, use vtkMRMLSequenceBrowserNode::SetColumnTitle method instead");
```

2023-10-25 15:51 UTC, Papa96108 commented
Hi @jcfr  thanks for your suggestion should I rewrite my commit message for commit message you suggest with git rebase?

2023-10-26 11:15 UTC, Papa96108 commented
@jcfr please run the workflow

2023-10-27 17:14 UTC, Papa96108 commented
The revert commit message always causes the check commit message workflow to fail can you help me find a solution i've already used git rebase to change the commit message without success. 

https://github.com/Slicer/Slicer/commit/0d06e8deeffaf2a4d21947f830dd9131537f4c77.
@lassoan 
@pieper 
@jcfr 
@mhdiop

2023-10-28 08:51 UTC, mhdiop commented
Thank you @Papa96108  for working on this issue.

We can have a Meet tonight to discuss about the difficulties you are facing.

Regards.

2023-10-28 08:53 UTC, Papa96108 commented
> Thank you @Papa96108 for working on this issue.
> 
> We can have a Meet tonight to discuss about the difficulties you are facing.
> 
> Regards.

Thanks you @mhdiop see you tonight

2023-11-29 16:11 UTC, lassoan commented
I've reviewed and fixed up the code, it all looks good now. Modules that provide translatable column name can enable `UseColumnTitleAsColumnHeader` to display that in the header (instead of displaying the column name).

> * Will the update changing `SCHEMA_COLUMN_LONG_NAME` to `SCHEMA_COLUMN_TITLE` impact loading of table saved using the older column name ?

I've added `ReadLongNameAsTitle` flag to allow using `longName` as `title`, but since often longName is too long for title, it is disabled by default. The only known use of longName is in Segment Statistics result tables, and there longName is too long.

2023-11-30 15:00 UTC, lassoan commented
@jcfr You have requested changes earlier, please have a look and approve if it looks good to you.

2023-12-06 13:39 UTC, merged

2023-12-06 14:15 UTC, jcfr commented
@lassoan Would it be sensible to integrate this one into `5.6.1` ?

2023-12-06 14:16 UTC, lassoan commented
Yes, I think so.