COMP: Use `GetLayoutName()` instead of `GetActiveTag()`
Slicer/Slicer pull request #7373
Opened 2023-11-09 23:39 UTC by jhlegarreta

Use `vtkMRMLCameraNode::GetLayoutName()` instead of `vtkMRMLCameraNode::GetActiveTag()`.

Fixes:
```
vtkMRMLCameraNode.cxx:405   WARN| vtkMRMLCameraNode (0x55d39e09e730):
vtkMRMLCameraNode::GetActiveTag() is deprecated.
Use vtkMRMLCameraNode::GetLayoutName() instead.
```

raised when running the `vtkMRMLFiberBundleNodeTest1` in the SlicerDMRI extension.

2023-11-09 23:41 UTC, jhlegarreta commented
Not sure if this is right, just followed the warning when I ran the `vtkMRMLFiberBundleNodeTest1` test from the SlicerDMRI extension:
https://github.com/SlicerDMRI/SlicerDMRI

Did not rebuild Slicer locally and run again the test.

2023-11-11 07:44 UTC, jcfr commented
Since the `active` tag associate with the `Camera` element is obsolete, we should keep and improve the warning. Guidance on how to fix the root cause has been provided in:
* https://github.com/SlicerDMRI/SlicerDMRI/issues/212

2023-11-11 07:44 UTC, jcfr requested changes
Since the `active` tag associate with the `Camera` element is obsolete, we should keep and improve the warning. Guidance on how to fix the root cause has been provided in:
* https://github.com/SlicerDMRI/SlicerDMRI/issues/212

2023-11-11 17:52 UTC, jhlegarreta commented
Thanks @jcfr. Submitted https://github.com/SlicerDMRI/SlicerDMRI/pull/213. I assume this PR can be closed then.

2023-11-11 19:18 UTC, closed without merging