COMP: Declare methods prototypes
Slicer/Slicer pull request #7396
Opened 2023-11-15 22:03 UTC by jhlegarreta

Declare the `setEnableQtTesting` and `splashMessage` method prototypes for the `qSlicerApplicationHelper` class.

Fixes:
```
In file included from /work/Stable/Slicer-0/Base/QTApp/qSlicerApplicationHelper.h:77:0,
                 from inner-build/Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleGenericTest.cxx:38:
/work/Stable/Slicer-0/Base/QTApp/qSlicerApplicationHelper.txx:64:6:
 warning: ‘void {anonymous}::splashMessage(QScopedPointer<QSplashScreen>&, const QString&)’ defined but not used [-Wunused-function]
 void splashMessage(QScopedPointer<QSplashScreen>& splashScreen, const QString& message)
      ^~~~~~~~~~~~~
```

and
```
/work/Stable/Slicer-0/Base/QTApp/qSlicerApplicationHelper.txx:53:6:
 warning: ‘void {anonymous}::setEnableQtTesting()’ defined but not used [-Wunused-function]
 void setEnableQtTesting()
      ^~~~~~~~~~~~~~~~~~
```

raised for the SlicerDMRI extenstion build in:
https://slicer.cdash.org/viewBuildError.php?type=1&buildid=3210886

2023-11-15 22:04 UTC, jhlegarreta commented
Not sure if this will make the warnings go away; have not tested locally.

2023-11-16 08:04 UTC, jcfr requested changes
It should be fixed using an approach similar to the one implemented in these patches:
* https://github.com/Slicer/Slicer/commit/53fea52c122ad7a1fd6055e3d1c4c96b546a2489 (`COMP: Fix -Wunused-function warnings in qMRMLLayoutManager tests`)
* https://github.com/commontk/CTK/commit/f6e9a1aace53d64669444723fd25bbf8e6815393 (`COMP: Fix -Wunused-function warnings in ctkErrorLogModelTestHelper`)

I also suspect this is specific to `GCC 7` used in the Slicer build environment[^1] `slicer/buildenv-qt5-centos7:latest`

I am not able to reproduce locally using `GCC 9.4.0` despite of making sure the  CXX flag `-Wunused-function` is used.

[^1]: https://github.com/Slicer/SlicerBuildEnvironment

2023-11-16 13:47 UTC, jhlegarreta commented
@jcfr thanks for the insight. 

> It should be fixed using an approach similar to the one implemented in these patches:

Are both things necessary? According to your hypothesis, the changes are to be done in `SlicerDMRI`, and not here. Is this correct?

However, I'd say that the error stems from the fact that they were not declared as `static`. I will give this a try first, if you agree.

I ignore why CentOS is used but support for it will end on 2024-06-30.

2023-11-16 13:58 UTC, jcfr commented
> I ignore why CentOS is used but support for it will end on 2024-06-30.

It is needed to allow Slicer to run on most linux distribution. This matches https://peps.python.org/pep-0599/#the-manylinux2014-policy

2023-11-16 14:00 UTC, jcfr commented
> the changes are to be done in SlicerDMRI

Not exactly, they would likely have to be done in Slicer but in `qSlicerModuleWidgetGenericTest.cxx.in`[^1].

[^1]: https://github.com/Slicer/Slicer/blob/2c7136165ac387985dac9947784ced43b556c37d/Base/QTGUI/Testing/Cxx/qSlicerModuleWidgetGenericTest.cxx.in

2023-11-16 16:15 UTC, jhlegarreta commented
I will amend the commit message once the right approach makes the tests pass.

2023-11-16 18:13 UTC, jhlegarreta commented
Still happening:
https://github.com/Slicer/Slicer/actions/runs/6894152495/job/18755324113?pr=7396#step:4:13360

2023-11-16 18:42 UTC, jcfr approved these changes
Local testing was successful. 

Once the CI also confirm the warning is addressed, this is now good for integration.

2023-11-16 23:17 UTC, merged