COMP: Fix ITK's threading-related method name deprecation warnings
Slicer/Slicer pull request #7400
Opened 2023-11-16 22:15 UTC by jhlegarreta

Fix ITK's threading-related method name deprecation warnings.

Fixes:
```
Slicer/Modules/CLI/ResampleDTIVolume/Testing/itkDifferenceDiffusionTensor3DImageFilter.txx:135:7:
 warning: ‘slicer_itk::ThreadIdType slicer_itk::ProcessObject::GetNumberOfThreads() const’ is deprecated [-Wdeprecated-declarations]
   int numberOfThreads = this->GetNumberOfThreads();
       ^~~~~~~~~~~~~~~
In file included from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkLightObject.h:21:0,
                 from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkMultiThreaderBase.h:31,
                 from /usr/src/Slicer-build/ITK/Modules/Compatibility/Deprecated/include/itkMultiThreader.h:23,
                 from /usr/src/Slicer/Modules/CLI/ResampleDTIVolume/Testing/itkTestMainExtended.h:41,
                 from /usr/src/Slicer/Modules/CLI/ResampleDTIVolume/Testing/ResampleDTIVolumeTest.cxx:9:
Slicer-build/ITK/Modules/Core/Common/include/itkProcessObject.h:499:31: note: declared here
   itkLegacyMacro(ThreadIdType GetNumberOfThreads() const) { return this->GetNumberOfWorkUnits(); }
                               ^
```

and
```
Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:925:60:
 warning: ‘void slicer_itk::ProcessObject::SetNumberOfThreads(slicer_itk::ThreadIdType)’ is deprecated [-Wdeprecated-declarations]
         transformDeformationFieldFilter->SetNumberOfThreads( list.numberOfThread );
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkLightObject.h:21:0,
                 from /usr/src/Slicer-build/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from /usr/src/Slicer/Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DResample.h:17,
                 from /usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:15:
Slicer-build/ITK/Modules/Core/Common/include/itkProcessObject.h:497:23: note: declared here
   itkLegacyMacro(void SetNumberOfThreads(ThreadIdType count)) { this->SetNumberOfWorkUnits(count); }
                       ^
```

raised for example in:
https://github.com/Slicer/Slicer/actions/runs/6885650499/job/18730113110#step:4:3902 and
https://github.com/Slicer/Slicer/actions/runs/6885650499/job/18730113110#step:4:3942

2023-11-16 23:44 UTC, jcfr commented
This pull request is a follow-up of https://github.com/Slicer/Slicer/commit/c6ff05d532b1c75b1617a0fbef74e5e5c7f55d73 (`BUG: Fix ITK filters to use ITKv5 dynamic multi threading`)

Relevant section of the ITK migration guide is [itk_5_migration_guide.md#multithreading-refactored](https://github.com/InsightSoftwareConsortium/ITK/blob/fd076e4db29144b56ff2a96a12baa263432daaab/Documentation/docs/migration_guides/itk_5_migration_guide.md#multithreading-refactored)

2023-11-16 23:47 UTC, jcfr commented
To move forward with this, the associated modules would likely need to be refactored.

2023-11-16 23:53 UTC, jcfr requested changes
In addition of remaining warnings, the build is currently failing with there errors:

```
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:200:34: error: ‘using ObjectType = class slicer_itk::DiffusionTensor3DInterpolateImageFunctionReimplementation<float, double> {aka class slicer_itk::DiffusionTensor3DInterpolateImageFunctionReimplementation<float, double>}’ has no member named ‘SetNumberOfWorkUnits’; did you mean ‘SetNumberOfThreads’?
     itkReimplementationInterpol->SetNumberOfWorkUnits( numberOfThreads );
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
     SetNumberOfThreads
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:208:26: error: ‘using ObjectType = class slicer_itk::DiffusionTensor3DBSplineInterpolateImageFunction<float, double> {aka class slicer_itk::DiffusionTensor3DBSplineInterpolateImageFunction<float, double>}’ has no member named ‘SetNumberOfWorkUnits’; did you mean ‘SetNumberOfThreads’?
     bSplineInterpolator->SetNumberOfWorkUnits( numberOfThreads );
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

and 

```
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:1154:31:   required from here
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:172:21: error: ‘using ObjectType = class slicer_itk::DiffusionTensor3DLinearInterpolateFunction<double, double> {aka class slicer_itk::DiffusionTensor3DLinearInterpolateFunction<double, double>}’ has no member named ‘SetNumberOfWorkUnits’; did you mean ‘SetNumberOfThreads’?
     linearInterpol->SetNumberOfWorkUnits( numberOfThreads );
     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
     SetNumberOfThreads
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:200:34: error: ‘using ObjectType = class slicer_itk::DiffusionTensor3DInterpolateImageFunctionReimplementation<double, double> {aka class slicer_itk::DiffusionTensor3DInterpolateImageFunctionReimplementation<double, double>}’ has no member named ‘SetNumberOfWorkUnits’; did you mean ‘SetNumberOfThreads’?
     itkReimplementationInterpol->SetNumberOfWorkUnits( numberOfThreads );
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
     SetNumberOfThreads
/usr/src/Slicer/Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx:208:26: error: ‘using ObjectType = class slicer_itk::DiffusionTensor3DBSplineInterpolateImageFunction<double, double> {aka class slicer_itk::DiffusionTensor3DBSplineInterpolateImageFunction<double, double>}’ has no member named ‘SetNumberOfWorkUnits’; did you mean ‘SetNumberOfThreads’?
     bSplineInterpolator->SetNumberOfWorkUnits( numberOfThreads );
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
     SetNumberOfThreads
```

2023-11-17 00:04 UTC, jhlegarreta commented
Yes, I've seen the errors; unclear to me how to move forward doing only minimal changes, maybe replicating this:

https://github.com/InsightSoftwareConsortium/ITK/blob/fd076e4db29144b56ff2a96a12baa263432daaab/Modules/Core/Common/include/itkProcessObject.h#L497C1-L501C29

in e.g.
https://github.com/Slicer/Slicer/blob/b41abc4f69a7f99253f6880733be97186dbfbd77/Modules/CLI/ResampleDTIVolume/itkDiffusionTensor3DRead.h#L67

and other affected classes.

2023-11-17 16:27 UTC, jhlegarreta commented
The warnings at issue are gone.

2023-12-22 12:17 UTC, jhlegarreta commented
Pinging @jcfr.

2024-01-14 08:06 UTC, jhlegarreta commented
Pinging @jcfr.

2024-01-17 15:42 UTC, jhlegarreta commented
Folks, can we please move forward with this? The draft label no longer applies to this PR, ITK's changes were introduced with ITKv5 6 years ago, and this would remove a number of warnings from the builds. Thanks for your time and work.

2024-01-17 17:23 UTC, pieper commented
@jhlegarreta you said the warnings are fixed, but I assume you mean the build errors are fixed too?  Are there any remaining issues?

2024-01-17 17:31 UTC, jhlegarreta commented
> @jhlegarreta you said the warnings are fixed, but I assume you mean the build errors are fixed too? Are there any remaining issues?

CIs are passing, isn't it? As said, the warnings this PR aims to remove are effectively removed. There are no remaining issues that this PR intends to fix.

2024-01-17 17:32 UTC, pieper commented
I was referring to the issue Jc noted above https://github.com/Slicer/Slicer/pull/7400#pullrequestreview-1735753104

2024-01-17 17:41 UTC, jhlegarreta commented
> I was referring to the issue Jc noted above https://github.com/Slicer/Slicer/pull/7400#pullrequestreview-1735753104

There have been multiple push forces since then and CIs are passing, so those issues are fixed.

2024-01-19 10:21 UTC, jhlegarreta commented
There are no standing issues with this PR, so can this be merged so that the number of build warnings is reduced, please? Thanks.

2024-01-19 16:35 UTC, jcfr commented
The last update[^1] effectively address the build error :white_check_mark:  

[^1]: https://github.com/Slicer/Slicer/compare/8529072c8086e0b977c645403ed870bd92e42a22..715254a4dc1f935d8db48fd0ca505705f487111b

2024-01-19 16:40 UTC, jcfr commented
The solution was to keep the API associated with the custom Slicer class `DiffusionTensor3DInterpolateImageFunctionReimplementation` unchanged and only replace `SetNumberOfThreads` with `SetNumberOfWorkUnits` for the ITK classes.

2024-01-19 16:46 UTC, jcfr approved these changes

2024-01-19 16:46 UTC, merged