BUG: Fix installation issue with qtwebengine components
Slicer/Slicer pull request #7539
Opened 2024-01-12 05:50 UTC by RafaelPalomar

This commit addresses the problem encountered during the installation of qtwebengine components when the `Slicer_BUILD_WEBENGINE_SUPPORT` option is disabled. By implementing the necessary fixes, we ensure that the installation process operates smoothly in both scenarios.

2024-01-19 21:38 UTC, jcfr commented
> addresses the problem encountered during the installation of qtwebengine components

Would you have more details regarding the original problem ?

2024-01-19 21:44 UTC, jcfr commented
Since the ICU libraries (along side with `icudtl.dat` from the `resources` directory) are dependency of many other libraries, we can not exclude them as you suggest.


<details><summary>Dependency of Qt libraries on ICU</summary>

```
export LD_LIBRARY_PATH=/home/jcfr/Support/Qt/5.15.2/gcc_64/lib

cd /home/jcfr/Support/Qt/5.15.2/gcc_64/lib

for lib in $(fd -e so); do echo "$lib"; ldd $lib | ack icu; done

lib/libQt53DAnimation.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f7be772d000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f7be7375000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f7be5990000)
lib/libQt53DCore.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fc718b8b000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fc7187d3000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fc716df0000)
lib/libQt53DExtras.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fddd3b7c000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fddd37c4000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fddd1de1000)
lib/libQt53DInput.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f89eedcb000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f89eea13000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f89ed030000)
lib/libQt53DLogic.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fc050d43000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fc05098b000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fc04efa8000)
lib/libQt53DQuick.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f91f98d3000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f91f951b000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f91f7b38000)
lib/libQt53DQuickAnimation.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fe582eba000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fe582b00000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fe58111d000)
lib/libQt53DQuickExtras.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f115efc0000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f115ec08000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f115d225000)
lib/libQt53DQuickInput.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f9068507000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f906814f000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f906676a000)
lib/libQt53DQuickRender.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fc392f7d000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fc392bc5000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fc3911e0000)
lib/libQt53DQuickScene2D.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f6750fe1000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f6750c29000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f674f244000)
lib/libQt53DRender.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f0bedd4c000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f0bed994000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f0bebfb1000)
lib/libQt5Bluetooth.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f9828d08000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f9828950000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f9826f6b000)
lib/libQt5Concurrent.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f7b68f30000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f7b68b78000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f7b67195000)
lib/libQt5Core.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007faa4c7fe000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007faa4c446000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007faa4aa63000)
lib/libQt5DBus.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f677c821000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f677c469000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f677aa86000)
lib/libQt5Designer.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f555b881000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f555b4c7000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f5559ae4000)
lib/libQt5DesignerComponents.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f65b4f3d000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f65b4b85000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f65b31a2000)
lib/libQt5EglFSDeviceIntegration.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f8f9d7b3000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f8f9d3fb000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f8f9ba18000)
lib/libQt5EglFsKmsSupport.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f0258d22000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f025896a000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f0256f87000)
lib/libQt5Gamepad.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fd47cc47000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fd47c88f000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fd47aeac000)
lib/libQt5Gui.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fd7585a9000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fd7581f1000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fd75680e000)
lib/libQt5Help.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007f8e166a1000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007f8e162e9000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007f8e14906000)
lib/libQt5Location.so
	libicui18n.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicui18n.so.56 (0x00007fa604581000)
	libicuuc.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicuuc.so.56 (0x00007fa6041c9000)
	libicudata.so.56 => /home/jcfr/Support/Qt/5.15.2/gcc_64/lib/libicudata.so.56 (0x00007fa [...]

2024-01-19 21:47 UTC, jcfr requested changes
Since by default the Qt 5 libraries installed using the official installer all depend on the ICU ones, we can't exclude the ICU libraries are associated resources simply by checking `Slicer_BUILD_WEBENGINE_SUPPORT`.

Before moving forward, we will need to better understand the use case.

2024-01-24 13:31 UTC, closed without merging

2024-01-24 13:31 UTC, RafaelPalomar commented
@jcfr, thanks for having a look at this. This issue is in connection with our discussion on flatpaks. I was playing with some ideas about distribution of Slicer, Slicer-based apps and extensions and found out that `cpack` failed when `Slicer_BUILD_WEBENGINE_SUPPOR=OFF`. I can't reproduce this, though, in `Slicer:main` and that means that it's either specific to the flatpak patched Slicer or that the issue was fixed already (I'm flat-packing Slicer stable).

We can close this now. I'll have a closer look to the issue and see if it affects `Slicer:main` and re-open if needed.