STYLE: Consistent formatting and indentation of C++ sources
Slicer/Slicer pull request #7603
Opened 2024-02-23 22:37 UTC by jcfr

This pull request ensures consistent indentation and formatting of for C++ source files.

It introduces `clang-format` configuration files as well as `pre-commit` configuration ensuring that IDE can appropriately format the code and continuous integration workflow can report when improperly formatted code is contributed.

Once integrated, this commit will be added to the `.git-blame-ignore-revs`[^1] file.

[^1]: https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs

## Open Questions

* Should we set `AlignConsecutiveAssignments`[^2] to `true` ?
* Should we customized the penalties[^3] ?
* Should we add additional `clang-format` exceptions ?

[^2]: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutiveassignments
[^3]: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#penaltybreakassignment

### Penalties

Default value for penalties are defined as such[^4]:

```cpp
  LLVMStyle.PenaltyBreakAssignment = prec::Assignment;
  LLVMStyle.PenaltyBreakComment = 300;
  LLVMStyle.PenaltyBreakFirstLessLess = 120;
  LLVMStyle.PenaltyBreakString = 1000;
  LLVMStyle.PenaltyExcessCharacter = 1000000;
  LLVMStyle.PenaltyReturnTypeOnItsOwnLine = 60;
  LLVMStyle.PenaltyBreakBeforeFirstCallParameter = 19;
  LLVMStyle.PenaltyBreakOpenParenthesis = 0;
  LLVMStyle.PenaltyBreakTemplateDeclaration = prec::Relational;
  LLVMStyle.PenaltyIndentedWhitespace = 0;
```

[^4]: https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/clang/lib/Format/Format.cpp#L1559-L1568

2024-02-23 22:42 UTC, jcfr commented on Base/QTGUI/qSlicerModuleSelectorToolBar.cxx
> +                   SLOT(setToolButtonStyle(Qt::ToolButtonStyle)));
Are we okay with this type of change ?

2024-02-26 22:45 UTC, pieper reviewed
I spot checked and didn't see anything I can't live with.

2024-02-27 16:23 UTC, cpinter commented
Thanks @jcfr it looks good!

I would not enable `AlignConsecutiveAssignments` because when we rename variables the alignment falls apart, and I prefer not to have anything badly aligned as opposed to not aligned at all. Cleaner in terms of number of unnecessary characters too.

I don't have specific suggestion about the penalties, anything reasonable will be fine with me.

2024-02-27 22:43 UTC, jcfr commented
Following today's Slicer weekly meeting[^1], we decided to delayed the integration.

We will first work to incrementally integrate formatting changes using `uncrustify`, this will help reduce the diff and experiment with different options to better assess the impact of line break changes specific to clang-format.

[^1]: https://discourse.slicer.org/t/2024-02-27-weekly-meeting/34553

2024-02-27 22:52 UTC, jcfr commented
Thanks @pieper, @cpinter, @lassoan @RafaelPalomar, @jamesobutler and @sjh26  for the review and feedback :pray:

2024-04-17 02:20 UTC, hjmjohnson commented on Base/QTGUI/qSlicerModuleSelectorToolBar.cxx
> +                   SLOT(setToolButtonStyle(Qt::ToolButtonStyle)));
Yes.

2024-04-17 02:22 UTC, hjmjohnson commented
Consistent automatic formatting is a great improvement.

2025-01-24 17:56 UTC, arhowe00 commented
Also #7621

2025-07-09 22:27 UTC, jcfr commented
This is now ready for final review :rocket: 

Each commits should be _reviewable_ on its own.

2025-07-10 02:16 UTC, hjmjohnson submitted a review, later dismissed
One comments for consideration that should not hold this up:

1) I like putting all the defaults in the .clang-config explicitly
```bash
clang-format --dump-config > AllDefaults.config ; 
mv AllDefaults.config .clang-format
```
so that if clang changes the default values, the code format does not change without explicit control.

Comment:  I'm fine with the first several partial change commits, but do not understand how they help.  It seems like a lot of work to do the incremental changes.  I'm fine with the work being done, and certainly don't want to add more work to simplify the changes. I just don't see the benefit of incremental formatting changes.

2025-07-10 02:22 UTC, hjmjohnson commented
@jcfr Manual rebase needs to be done to navigate each of the small change commits.

2025-07-10 03:37 UTC, jcfr commented
> I fine with the first several partial change commits, but do not understand how they help. It seems like a lot of work to do the incremental changes. I'm fine with the work being done, and certainly don't want to add more work to simplify the changes. I just don't see the benefit of incremental formatting changes.


The incremental commits were completed over the course of a few hours and proved essential for understanding the full impact of the code restructuring introduced by `clang-format` (cc: @lassoan), while keeping the changes deterministic and reviewable.

For example, working incrementally helped surface an issue where `clang-format` introduced an extra space before the `::` scope resolution operator (e.g., `ClassName ::Something`). Addressing this required a small `sed` script and re-running `clang-format` to restore consistency (see the commit message for `STYLE: Consistent formatting of C++ sources using clang-format`). It also revealed that `.txx` files were not handled by default, which led to customizing the pre-commit configuration.

Beyond that, the normalization commits helped apply consistent formatting to commented-out code, docstrings, and even Markdown documentation—cases that would have otherwise been missed in a bulk pass.

--------------------

> Manual rebase needs to be done to navigate each of the small change commits

Since the changes associated with each commit were scripted (including staging and invoking `git commit`) ... ebasing has been straightforward.

The process is fully reproducible, making it easy to review, adjust, or reapply changes as needed

2025-07-10 03:49 UTC, jcfr commented
> I like putting all the defaults in the `.clang-format` explicitly [...] so that if clang changes the default values, the code format does not change without explicit control.

After reviewing the commit history of `Format.cpp`[^1], where default values are defined, it appears that these defaults do not change frequently across versions. For this reason, I prefer keeping the `.clang-format` file lean, making it easier to identify which settings are intentional overrides rather than inherited defaults.

Additionally, since the version of `clang-format` is explicitly pinned in `.pre-commit-config.yaml` (i.e. `20.1.7`), any version upgrade will be a deliberate change ... at which point we can review and adjust the config as needed (e.g., to add, remove, or rename options based on upstream changes).

[^1]: https://github.com/llvm/llvm-project/commits/llvmorg-20.1.7/clang/lib/Format/Format.cpp

2025-07-10 05:32 UTC, lassoan commented
@jcfr @hjmjohnson Thank you very much for working on this. I've randomly sampled 60 source files and the overwhelming majority of the changes make the code better, more consistently formatted!

In this random sampling, I haven't found any cases when readability was significantly worsened.

1. I've found one potentially wrong processing (quotes did not close in the line), but it was in a commented out code section (in vtkMRMLAnnotationStorageNode.cxx), so probably we can ignore it:

```
    {
    vtkWarningMacro("ReadData: refNode " << refNode->GetName() << " is in a hierarchy, " << hnode->GetName() << ",
  assuming that it read it in already"); return 1;
    }
```

2. There is one systematic change that I don't find beneficial is aligning method arguments, because it wastes a lot of space (but I do not object to introduce it it if others have no problem with it)

Example generated code:

```
      if (std::string(oldID) == std::string(reference->GetReferencedNodeID()))
      {
        this->SetAndObserveNthNodeReferenceID(reference->GetReferenceRole(),
                                              i,
                                              newID,
                                              reference->GetStaticEvents(),
                                              reference->GetObserveContentModifiedEvents());
      }
```

I would prefer this instead:

```
      if (std::string(oldID) == std::string(reference->GetReferencedNodeID()))
      {
        this->SetAndObserveNthNodeReferenceID(reference->GetReferenceRole(),
          i, newID, reference->GetStaticEvents(), reference->GetObserveContentModifiedEvents());
      }
```

---

Example generated code:

```
//----------------------------------------------------------------------------
vtkMRMLNode* vtkMRMLNode::SetAndObserveNthNodeReferenceID(const char* referenceRole,
                                                          int n,
                                                          const char* referencedNodeID,
                                                          vtkIntArray* staticEvents,
                                                          ContentModifiedObserveType observeContentModifiedEvents)
{
```

I would prefer this instead:

```
//----------------------------------------------------------------------------
vtkMRMLNode* vtkMRMLNode::SetAndObserveNthNodeReferenceID(const char* referenceRole,
  int n, const char* referencedNodeID, vtkIntArray* staticEvents, ContentModifiedObserveType observeContentModifiedEvents)
{
```

Example generated code:

```
    }
    else if (this->IsReferenceRoleGeneric(nodeReferenceRole.c_str())
             && (attributeName.length() >= nodeMRMLAttributeName.length())
             && attributeName.compare(attributeName.length() - nodeMRMLAttributeName.length(),
                                      nodeMRMLAttributeName.length(),
                                      nodeMRMLAttributeName)
                  == 0)
    {
```

I would prefer this instead:

```
    }
    else if (this->IsReferenceRoleGeneric(nodeReferenceRole.c_str())
             && (attributeName.length() >= nodeMRMLAttributeName.length())
             && attributeName.compare(attributeName.length() - nodeMRMLAttributeName.length(),
               nodeMRMLAttributeName.length(), nodeMRMLAttributeName) == 0)
    {
```

Example generated code:

```
      {
        vtkErrorMacro("Error while writing node " << (this->GetID() ? this->GetID() : "(unknown)")
                                                  << " to XML: data node is invalid at index value "
                                                  << indexIt->IndexValue);
      }
```

I would prefer this instead:

```
      {
        vtkErrorMacro("Error while writing node " << (this->GetID() ? this->GetID() : "(unknown)")
          << " to XML: data node is invalid at index value " << indexIt->IndexValue);
      }
```

3. Other than these, the formatter created some clumsy, odd-looking code due to:
- a. the source code was already not well organized (e.g., too long line, not well positioned comment, ...), or
- b. unlucky cases when a line was just a bit too long

There is not much to do with a) automatically. Developers can fix up the formatting by reorganizing the code.

For b), it could be useful if the formatting rules could be tuned to only break up a line into multiple lines if there is significant benefit (the line gets at least 20 character shorter). But if changing this rule would have side effects or cause complications elsewhere then it is OK to keep the current settings.

Example generated code:

```
  {
    QObject::connect(
      plugin, SIGNAL(requestExpandItem(vtkIdType)), q, SLOT(expandItem(vtkIdType)), Qt::UniqueConnection);
    QObject::connect(
      plugin, SIGNAL(requestInvalidateFilter()), q->model(), SIGNAL(invalidateFilter()), Qt::UniqueConnection);
  }
```

I would prefer this instead:

```
  {
    QObject::connect(plugin, SIGNAL(requestExpandItem(vtkIdType)), q, SLOT(expandItem(vtkIdType)), Qt::UniqueConnection);
    QObject::connect(plugin, SIGNAL(requestInvalidateFilter()), q->model(), SIGNAL(invalidateFilter()), Qt::UniqueConnection);
  }

```

Example generated code:

```
  Q_OBJECT
  Q_PROPERTY(
    QString currentNodeID READ currentNodeID WRITE setCurrentNodeID NOTIFY currentNodeIDChanged DESIGNABLE false)
  Q_PROPERTY(QString currentNodeId READ currentNodeId WRITE setCurrentNode DESIGNABLE false) // \deprecated
```

I would prefer this instead:

```
  Q_OBJECT
  Q_PROPERTY(QString currentNodeID READ currentNodeID WRITE setCurrentNodeID NOTIFY currentNodeIDChanged DESIGNABLE false)
  Q_PROPERTY(QString currentNodeId READ currentNodeId WRITE setCurrentNode DESIGNABLE false) // \deprecated
```

Example generated code:

```
  Q_PROPERTY(bool clippingConfigurationButtonVisible READ clippingConfigurationButtonVisible WRITE
               setClippingConfigurationButtonVisible)
```

I would prefer this instead:

```
  Q_PROPERTY(bool clippingConfigurationButtonVisible READ clippingConfigurationButtonVisible WRITE setClippingConfigurationButtonVisible)
```

2025-07-10 17:16 UTC, hjmjohnson commented
@lassoan Regarding #2 above.  I have a slight reading disability, and I find the new aligned code much easier to read and understand.  It does take up more real estate, but for me,  the new code is MUCH easier to read.  I'm OK with whatever the final decision is.

Regarding #3 above.  I agree with you, but I think that the ability to globally automate formatting consistently far outweighs the small degradation in some of these individual cases.

2025-07-10 17:17 UTC, hjmjohnson submitted a review, later dismissed
Thanks @jcfr JC!!!

2025-07-10 17:49 UTC, hjmjohnson commented
FYI:  A suggested mechanism to update an existing branch so that each commit meets the requirements
of the enforced pre-commit items.

```bash
#!/bin/bash
#
# This script documents how to update a branch
# to apply pre-commit enforcements to every commit

#branch_to_rebase_from=$1
branch_to_rebase_from=jcfr/style-consistently-indent-cpp-files

echo "For each commit that required changes,\n
git add -p # <- Review the changes made and add them
git commit --amend # <- amend the commit 
git rebase --continue # <- goto next commit
"
git rebase --exec "pre-commit run --from-ref HEAD~1 --to-ref HEAD --hook-stage=commit" ${branch_to_rebase_from}
```

2025-07-10 18:10 UTC, lassoan approved these changes

2025-07-10 18:55 UTC, jcfr commented
As a trade-off and to address @lassoan comment, I bumped the column limit from `120` to `180` and this seems to address some of the concern.


This is also seems to include most of the lines before `clang-reformat` was applied:

```
/path/to/line_length_histogram.sh 180
Line Length Histogram:
  0-  9: 200244
 10- 19: 40583
 20- 29: 44773
 30- 39: 52417
 40- 49: 46224
 50- 59: 40752
 60- 69: 42380
 70- 79: 45884
 80- 89: 24880
 90- 99: 11373
100-109: 7368
110-119: 4941
120-129: 3078
130-139: 1816
140-149: 1178
150-159: 647
160-169: 159
170-179: 63
180-189: 34
190-199: 17
200-209: 18
210-219: 13
220-229: 2
230-239: 69
240-249: 2
250-259: 1
270-279: 2
300-309: 2
320-329: 1
330-339: 1
340-349: 1
390-399: 1
410-419: 1
590-599: 1

Files with at least one line longer than 180 characters:
./Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.h
./Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
./Libs/vtkSegmentationCore/vtkOrientedImageDataResample.h
./Modules/CLI/ModelMaker/ModelMaker.cxx
./Libs/vtkSegmentationCore/vtkClosedSurfaceToFractionalLabelmapConversionRule.cxx
./Libs/vtkSegmentationCore/vtkOrientedImageDataResample.cxx
./Libs/MRML/Core/vtkMRMLCoreTestingMacros.h
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationFiducialsStorageNode.cxx
./Libs/MRML/Core/vtkMRMLNode.h
./Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.h
./Libs/MRML/Logic/vtkMRMLSliceLogic.cxx
./Libs/MRML/Logic/vtkMRMLSliceLogic.h
./Libs/MRML/Core/vtkMRMLSegmentationStorageNode.cxx
./Libs/MRML/Core/vtkMRMLNode.cxx
./Libs/MRML/Logic/vtkMRMLColorLogic.h
./Modules/CLI/ResampleDTIVolume/Testing/ResampleDTIVolumeTest.cxx
./Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologiesModuleLogic.h
./Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.h
./Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractEffect.cxx
./Libs/MRML/Core/vtkMRMLROIListNode.cxx
./Libs/MRML/Core/Testing/vtkMRMLSceneImportIDModelHierarchyConflictTest.cxx
./Libs/MRML/Core/vtkDataFileFormatHelper.cxx
./Libs/MRML/Core/Testing/vtkMRMLHierarchyNodeTest3.cxx
./Modules/Loadable/Segmentations/Widgets/qMRMLSegmentationRepresentationsListView.cxx
./Libs/vtkSegmentationCore/vtkSegmentationConverter.h
./Libs/MRML/Core/vtkMRMLScene.cxx
./Libs/vtkSegmentationCore/vtkSegmentation.cxx
./Libs/MRML/Core/vtkMRMLScalarVolumeDisplayNode.h
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesStorageNode.cxx
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationStorageNode.h
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationStorageNode.cxx
./Libs/vtkSegmentationCore/vtkPolyDataToFractionalLabelmapFilter.cxx
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationLinesStorageNode.h
./Libs/MRML/Core/Testing/vtkMRMLSceneImportIDModelHierarchyParentIDConflictTest.cxx
./Base/Logic/Testing/vtkSlicerApplicationLogicTest1.cxx
./Libs/vtkSegmentationCore/Testing/vtkSegmentationHistoryTest1.cxx
./Modules/Loadable/Segmentations/MRMLDM/vtkMRMLSegmentationsDisplayableManager2D.cxx
./Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorAbstractLabelEffect.cxx
./Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorPaintEffect_p.h
./Modules/Loadable/Volumes/Logic/vtkSlicerVolumesLogic.cxx
./Modules/Loadable/Segmentations/SubjectHierarchyPlugins/qSlicerSubjectHierarchySegmentationsPlugin.cxx
./Libs/MRML/DisplayableManager/vtkMRMLViewInteractorStyle.cxx
./Libs/MRML/Widgets/qMRMLSortFilterProxyModel.cxx
./Modules/Loadable/Models/Testing/Cxx/qSlicerModelsModuleWidgetTest.cxx
./Libs/MRML/Core/vtkMRMLTransformNode.cxx
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsStorageNode.cxx
./Modules/CLI/PETStandardUptakeValueComputation/PETStandardUptakeValueComputation.cxx
./Modules/Loadable/Annotations/MRML/vtkMRMLAnnotationControlPointsNode.cxx
./Libs/MRML/Core/vtkMRMLStorageNode.cxx
./Modules/Loadable/SubjectHierarchy/qSlicerSubjectHierarchyModule.cxx
./Libs/MRML/Core/Testing/vtkMRMLVolumeNodeTest1.cxx
./Modules/CLI/ResampleDTIVolume/ResampleDTIVolume.cxx

```

2025-07-10 19:08 UTC, jamesobutler approved these changes

2025-07-10 19:11 UTC, hjmjohnson approved these changes

2025-07-10 19:19 UTC, hjmjohnson commented
In file 'Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx' is longer than 160 characters.
  It is required to have no more than 80 characters per line
  
  ```
  ../Slicer/.git/hooks/pre-commit.legacy:  in file '$file' is longer than 160 characters.
  ```
  
FYI:
```txt
RUN:  SetupForDevelopment.sh
   CALLS: Slicer/Utilities/Scripts/SetupHooks.sh
   DOWNLOADS:  .git/hooks/pre-commit  #<-- our hand crafted legacy checker with linelimit of 160
RUN: pre-commit install
    MOVES:  .git/hooks/pre-commit  -> .git/hooks/pre-commit.legacy (which is run if it exists)
    CREATES: .git/hooks/pre-commit for the pre-commit infrastructure
```
  
```
% pre-commit install                                                                                                                                                                                             
     Running in migration mode with existing hooks at .git/hooks/pre-commit.legacy
     Use -f to use only pre-commit.
     pre-commit installed at .git/hooks/pre-commit
```

When you run pre-commit install, it notices you already have an existing pre-commit hook in .git/hooks/pre-commit that it did not create (i.e., not managed by pre-commit).

To avoid overwriting that hook, pre-commit:
	•	Moves the existing hook to .git/hooks/pre-commit.legacy
	•	Installs its own hook into .git/hooks/pre-commit
	•	Runs in “migration mode”, meaning it will also execute the legacy hook so your original behavior isn’t lost

2025-07-10 19:59 UTC, hjmjohnson requested changes
Modify the "SetupHooks.sh" to directly install a script to ".git/hooks/pre-commit.legacy" that has a 180 character line limit.

Perhaps modify Utilities/SetupForDevelopment.sh to include

```
# inspired from ITK
(Utilities/GitSetup/setup-precommit  ||
 echo 'Failed to setup pre-commit.') && echo &&
```

  In file 'Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx' is longer than 160 characters.
  It is required to have no more than 80 characters per line
  
  ```
  ../Slicer/.git/hooks/pre-commit.legacy:  in file '$file' is longer than 160 characters.
  ```
  
FYI:
```txt
RUN:  SetupForDevelopment.sh
   CALLS: Slicer/Utilities/Scripts/SetupHooks.sh
   DOWNLOADS:  .git/hooks/pre-commit  #<-- our hand crafted legacy checker with linelimit of 160
RUN: pre-commit install
    MOVES:  .git/hooks/pre-commit  -> .git/hooks/pre-commit.legacy (which is run if it exists)
    CREATES: .git/hooks/pre-commit for the pre-commit infrastructure
```
  
```
% pre-commit install                                                                                                                                                                                             
     Running in migration mode with existing hooks at .git/hooks/pre-commit.legacy
     Use -f to use only pre-commit.
     pre-commit installed at .git/hooks/pre-commit
```

When you run pre-commit install, it notices you already have an existing pre-commit hook in .git/hooks/pre-commit that it did not create (i.e., not managed by pre-commit).

To avoid overwriting that hook, pre-commit:
	•	Moves the existing hook to .git/hooks/pre-commit.legacy
	•	Installs its own hook into .git/hooks/pre-commit
	•	Runs in “migration mode”, meaning it will also execute the legacy hook so your original behavior isn’t lost

2025-07-10 20:29 UTC, jcfr commented
> re: Update of line length check in `SetupForDevelopment.sh`

This is now addressed in the following pull request:
* https://github.com/Slicer/Slicer/pull/8545

2025-07-11 00:25 UTC, jcfr commented
I am refining this topic by adding a few clang-format exceptions, I will update and integrate later in the evening. Thanks for the patience.

2025-07-11 12:28 UTC, hjmjohnson submitted a review, later dismissed

2025-07-11 22:44 UTC, jcfr commented
Et voilà! This is now ready for integration :rocket:

@lassoan To help preserve developer intent and formatting clarity, I’ve added two additional commits:

### STYLE: Add // comments to preserve wrapping before clang-format integration

This commit adds inline `//` comments at the end of multi-line expressions to prevent `clang-format` from collapsing them into single lines. These changes preserve intentional formatting and improve readability in preparation for automated formatting enforcement.

Examples of updated patterns include:

* Long `if` and `else if` conditions
* Multi-line `return` expressions
* Long chains of `&&` or `||`

### STYLE: Use clang-format off/on to preserve alignment and readability

This change adds `// clang-format off/on` off/on comments around selected blocks of code to prevent unwanted reformatting by clang-format. It ensures that aligned declarations, test data tables, and string literal comparisons remain readable and consistent.

2025-07-12 11:57 UTC, hjmjohnson approved these changes

2025-07-12 15:17 UTC, jcfr commented
I missed to maintain some of indentation in MRML tests ... patch applied are similar to this one:

```diff
+++ b/Libs/MRML/Core/Testing/vtkMRMLModelDisplayNodeTest1.cxx
@@ -203,11 +203,16 @@ int TestSetMesh(bool observeMeshBeforeObserveDisplay, bool observeDisplayBeforeA
       displayInputMesh != model->GetMesh() ||                                             //
       displayInputMesh != mesh)
   {
-    std::cerr << __LINE__ << ": vtkMRMLModelNode::SetAndobserveMesh failed when " << (meshTypeIsPolyData ? "surface" : "volumetric") << " mesh is set "
-              << (observeMeshBeforeObserveDisplay ? "before" : "after") << " the display node is observed and when the display node is "
-              << "added in the scene " << (observeDisplayBeforeAddToScene ? "before" : "after") << " the observation:\n"
-              << "Mesh: " << mesh << ", "
-              << "Model: " << model->GetMesh() << ", "
+    std::cerr << __LINE__ << ": vtkMRMLModelNode::SetAndobserveMesh failed when " //
+              << (meshTypeIsPolyData ? "surface" : "volumetric")                  //
+              << " mesh is set "                                                  //
+              << (observeMeshBeforeObserveDisplay ? "before" : "after")           //
+              << " the display node is observed and when the display node is "    //
+              << "added in the scene "                                            //
+              << (observeDisplayBeforeAddToScene ? "before" : "after")            //
+              << " the observation:\n"                                            //
+              << "Mesh: " << mesh << ", "                                         //
+              << "Model: " << model->GetMesh() << ", "                            //

```

2025-07-12 16:05 UTC, hjmjohnson submitted a review, later dismissed
@jcfr Thanks.  I hope some of this can get pushed soon.  I have many (similar to #8548 ) pending commits that will come soon after this is accepted.  (See the list of the first 8 commits on #8543 that can be cherry-picked after this is completed).

2025-07-12 16:16 UTC, jcfr commented
Thanks for the approval. Auto merge is enabled & this will be integrated as soon as CI completes 🚀👌

2025-07-12 16:43 UTC, jamesobutler commented
Apologies that the recent integration of #8427 has caused a merge conflict here.

2025-07-12 17:49 UTC, jcfr commented
> Apologies that the recent integration of https://github.com/Slicer/Slicer/pull/8427 has caused a merge conflict here.

No worry, this has just been addressed :white_check_mark: 

@hjmjohnson  @jamesobutler Once this is (re-)approved and CI checks are :100: , we should be all set :rocket:

2025-07-12 18:15 UTC, merged

2025-07-12 20:12 UTC, lassoan commented
Thanks to all for working on this!

Do you have any recommendation on how to update branches that were created before this formatting change? I have several branches with a number of commits and lots of modified files and now pretty much every modified line is a merge conflict. There are also 57 open PRs with the same issue. An automated script would be ideal.

2025-07-13 04:27 UTC, jamesobutler commented
A follow-up to this PR can be adding the integrated commits to https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs.