DOC: Update gui.md with example on how to display a node in only some views
Slicer/Slicer pull request #7708
Opened 2024-04-23 15:12 UTC by koegl

I stumbled upon this problem and couldn't find it in the forum or in the script repository (I also created a [post](https://discourse.slicer.org/t/how-to-show-a-fiducial-in-only-specified-views/35682/2) on discourse)

2024-04-23 19:01 UTC, jcfr commented on Docs/developer_guide/script_repository/gui.md
> +```
````suggestion
### Display a node in only some views

Show a displayable node in a predefined set of views. Here, show a markups line only in `Red+`, `Green+` and `Yellow+` views.

```
displayableNode = getNode("L")

viewNodeIDs = [
  slicer.app.layoutManager().sliceWidget(viewName).mrmlSliceNode().GetID()
  for viewName in ["Red+", "Green+", "Yellow+"]
]

displayableNode.GetDisplayNode().SetViewNodeIDs(viewNodeIDs)
````

For reference, here is a related issues:
* https://github.com/Slicer/Slicer/issues/7434

2024-04-23 19:03 UTC, jcfr requested changes
Thanks for the contribution :pray: 

Once you are able to review the suggested changes, we will move forward with the integration.

2024-04-24 03:32 UTC, lassoan submitted a review, later dismissed

2024-04-24 03:46 UTC, jcfr commented on Docs/developer_guide/script_repository/gui.md
> +displayableNode.GetDisplayNode().SetViewNodeIDs(viewNodeIDs)
````suggestion
displayableNode.GetDisplayNode().SetViewNodeIDs(viewNodeIDs)
```
````

2024-04-24 04:02 UTC, jamesobutler approved these changes

2024-04-24 04:11 UTC, merged