BUG: Fix ExtensionsIndex build
Slicer/Slicer pull request #8084
Opened 2024-12-10 01:28 UTC by lassoan

On Windows, cmake.exe path usually contain space (e.g., "C:/Program Files/CMake/bin/cmake.exe"). If such a string is passed to execute_process as COMMAND directly then the command returns "no such file or directory" error (due to "C:/Program" is not found).

Fixed by converting the semicolon-separated string to a list and using that list as COMMAND.

2024-12-10 22:47 UTC, lassoan commented
I'll proceed with merging this. If it turns out to cause any trouble on the factory machine (unlikely) then we can revert.

2024-12-10 23:08 UTC, jcfr requested changes

2024-12-10 23:08 UTC, jcfr commented on Extensions/CMake/SlicerBlockBuildPackageAndUploadExtensions.cmake
> +    string(REPLACE \";\" \";\" list \${wrapper_command_list})
The `list` variable does not seem to be used anywhere

2024-12-11 02:22 UTC, jcfr approved these changes

2024-12-11 03:25 UTC, merged