BUG: Fix build system for Ubuntu 22.04
Slicer/Slicer pull request #8111
Opened 2024-12-21 16:12 UTC by RafaelPalomar

This commit fixes Slicer/Slicer#8110 by adding a case for correct detection of `qt_root_dir` for Ubuntu multiarch directory structure.

2025-01-29 06:07 UTC, jcfr requested changes
Thanks for the contribution :pray:

2025-01-29 06:07 UTC, jcfr commented on CMake/SlicerBlockInstallQtTools.cmake
>    set(qt_root_dir "${_dir}/..")
```suggestion
  set(qt_root_dir "${_dir}/..")
  # "_dir" of the form "<qt_root_dir>/lib/<arch>" (e.g "<qt_root_dir>/lib/x86_64-linux-gnu")
  if("${_dir}" MATCHES "${CMAKE_LIBRARY_ARCHITECTURE}")
    set(qt_root_dir "${qt_root_dir}/..")
  endif()
```

This is a more general approach allowing to support other architecture (e.g arm64). See https://cmake.org/cmake/help/v3.31/variable/CMAKE_LIBRARY_ARCHITECTURE.html#cmake-library-architecture

2025-02-05 11:16 UTC, RafaelPalomar commented
@jcfr, thanks for your suggestions, they have been integrated in the PR. I tested this in Ubutu 22.04 and it solves Slicer/Slicer#8110

2025-02-05 16:31 UTC, jcfr reviewed
Thanks for moving forward with this :pray: 

Could you confirm that only relying on

```
  if("${_dir}" MATCHES "${CMAKE_LIBRARY_ARCHITECTURE}")
    set(qt_root_dir "${qt_root_dir}/..")
  endif()
```

is sufficient ?

2025-02-05 16:31 UTC, jcfr commented on CMake/SlicerBlockInstallQtTools.cmake
> +  set(qt_root_dir "${_dir}/../..")
```suggestion
```

2025-02-06 13:17 UTC, jcfr commented on CMake/SlicerBlockInstallQtTools.cmake
> +  # "_dir" of the form "<qt_root_dir>/lib/<arch>" (e.g "<qt_root_dir>/lib/x86_64-linux-gnu")
```suggestion
    # "_dir" of the form "<qt_root_dir>/lib/<arch>" (e.g "<qt_root_dir>/lib/x86_64-linux-gnu")
```

2025-02-06 13:22 UTC, jcfr commented
while I thinking about the commit message we would write to describe the change, I am realizing that what you we are trying to do is support creating a package in the context of Slicer being built on Qt5 being installed on the system ?

In that particular scenario, I think the "right" approach may be to improve the heuristic here:

https://github.com/Slicer/Slicer/blob/64deee1615824fe821f23bff9b46f3edef37dcd1/CMakeLists.txt#L704-L730

2025-02-06 14:16 UTC, RafaelPalomar commented
@jcfr, that's interesting. So in case qt is detected in the system `Slicer_USE_SYSTEM_QT` will be set to `ON`. Can we make the case that the user has QT installed in the system and does not want to use the system qt? I guess `-DQt5_DIR` would do the job for this case.

I'll try playing with the `CMakeLists.txt` and come back to you

2025-02-06 14:28 UTC, jcfr commented
Assuming we integrated the patch below, configuring with both `-DQt5_DIR:PATH=/path/to/lib/cmake/Qt5` and explicitly setting `-DSlicer_USE_SYSTEM_QT:BOOL=OFF` would allow to force the packaging of Qt dependencies being installed on the system.

I am curious to see if packaging on Ubuntu 22.04 and then trying to run Slicer on Ubuntu 24.04 without having Qt5 installed on the system would work.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c6d54b15ce9..de656b66aab 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -716,6 +716,7 @@ set(Slicer_HAVE_QT5 1)
 #
 # See https://issues.slicer.org/view.php?id=3574
 #
+if(NOT DEFINED Slicer_USE_SYSTEM_QT)
   foreach(_path IN ITEMS
       "/usr/lib/"
       "/usr/lib32/"
@@ -730,11 +731,12 @@ set(Slicer_HAVE_QT5 1)
     if("${Qt5_DIR}" MATCHES "^${_path}")
       set(Slicer_USE_SYSTEM_QT ON)
       message(STATUS "")
-      message(STATUS "Forcing Slicer_USE_SYSTEM_QT to ON (Qt5_DIR [${Qt5_DIR}] associated with a system location: ${_path})")
+      message(STATUS "Initializing Slicer_USE_SYSTEM_QT to ON (Qt5_DIR [${Qt5_DIR}] associated with a system location: ${_path})")
       message(STATUS "")
       break()
     endif()
   endforeach()
+endif()
 
 # Always use QVTKOpenGLWidget (instead of QVTKWidget)
 set(Slicer_VTK_USE_QVTKOPENGLWIDGET 1)
```

2025-02-09 11:08 UTC, RafaelPalomar commented
> Assuming we integrated the patch below, configuring with both `-DQt5_DIR:PATH=/path/to/lib/cmake/Qt5` and explicitly setting `-DSlicer_USE_SYSTEM_QT:BOOL=OFF` would allow to force the packaging of Qt dependencies being installed on the system.

I see. This makes sense. There seem to be some implications of the Debian usr-merge (https://wiki.debian.org/UsrMerge). On [f5ab263](https://github.com/Slicer/Slicer/pull/8111/commits/f5ab2633a71e789f40088cfe0e9652169f0bfa68) we expand the list of paths to cover for usr-merge and multiarch variants of paths. This should give good coverage for a wide range of scenarios. Tested on Ubuntu 22.04.

> I am curious to see if packaging on Ubuntu 22.04 and then trying to run Slicer on Ubuntu 24.04 without having Qt5 installed on the system would work.

I'm curious too. I can give this a try.

2025-02-09 11:25 UTC, jcfr approved these changes

2025-02-09 11:41 UTC, jcfr commented
Thanks for updating this pull request :pray:

I proposed to move forward with `Squash & Merge` specifying the following commit message:

```
COMP: Improve system Qt detection on Debian usr-merge and multiarch systems

On Debian-based distributions that implement usr-merge, `/lib` is a symlink
to `/usr/lib`. As a result, `Qt5_DIR` might end up pointing to a path under
`/lib`, which was not recognized as a system location. Additionally, on
multiarch systems, library directories often include architecture-specific
subfolders under `/usr/lib` or `/lib`.

This commit expands the list of paths checked when initializing `Slicer_USE_SYSTEM_QT`
to include `/lib`, `/lib/<arch>`, and `/usr/lib/<arch>` directories. This
ensures that Slicer correctly detects and uses the system Qt installation
on these configurations.

It also wraps the system Qt detection logic to support overriding the
initialization of `Slicer_USE_SYSTEM_QT`. This allows packaging of Qt
libraries and plugins even if Qt is installed on the system.

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
```

2025-02-09 11:49 UTC, jcfr commented
@RafaelPalomar Note that after trying to configure & package after specifying options as described in https://github.com/Slicer/Slicer/pull/8111#issuecomment-2639982987, we may still have to submit a follow-up pull request to fix `CMake/SlicerBlockInstallQtTools.cmake`, can I let you do so in a follow-up pull request ? 🙏

2025-02-09 18:44 UTC, merged